### ISSUE TITLE
A question about the derivative of x(t)

### ISSUE THREAD

**Issue by gongshuai0606** [kpchamp/SindyAutoencoders#4]
Hi, I wonder whether it is possible to approximate the derivative of x(t) numerically from x(t) when the equations are unknown

**Comment by kpchamp** [comment]
Yes, that is definitely possible! If you’re looking for approaches to estimate the derivatives numerically, you could check out [PySINDy](https://github.com/dynamicslab/pysindy) which has several approaches implemented.

**Comment by gongshuai0606** [comment]
> Yes, that is definitely possible! If you’re looking for approaches to estimate the derivatives numerically, you could check out [PySINDy](https://github.com/dynamicslab/pysindy) which has several approaches implemented.

Thank you very much
